---------------------------------
[2023-09-11 06:36:19][INFO][200]:La conexion [dbconn_standard] esta desabilitada en el archivo .config
---------------------------------
[2023-09-11 06:36:19][INFO][200]:Iniciando ...
---------------------------------
[2023-09-11 06:36:19][INFO][200]:Se van a inferir 11 entidades
---------------------------------
[2023-09-11 06:36:38][EXCEPTION][500]:PYTHON-EXCEPTION:

>>>>>>>>>>>>>>>[TRACEBACK]<<<<<<<<<<<<<<<

  File "/home/alanromero/crowd-counting/src/inference/main.py", line 10, in <module>
    ProjectDirector.go( sys.argv )
  File "/home/alanromero/crowd-counting/src/inference/System/Director/ProjectDirector.py", line 138, in go
    ProjectDirector().setFlux( argv )
  File "/home/alanromero/crowd-counting/src/inference/System/Director/ProjectDirector.py", line 118, in setFlux
    asyncio.run(self.__play(
  File "/home/alanromero/anaconda3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/alanromero/anaconda3/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/home/alanromero/anaconda3/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/home/alanromero/anaconda3/lib/python3.10/asyncio/base_events.py", line 1906, in _run_once
    handle._run()
  File "/home/alanromero/anaconda3/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/alanromero/crowd-counting/src/inference/System/Director/ProjectDirector.py", line 81, in __play
    person_entities = await infer.create_person_entities(camera_entities)
  File "/home/alanromero/crowd-counting/src/inference/System/App/InferProcedures/InferProcedures.py", line 59, in create_person_entities
    entities.append( await self.orion.infer(camera, decryptedF))
  File "/home/alanromero/crowd-counting/src/inference/System/App/OrionProcedures/OrionProcedures.py", line 105, in infer
    entities = self.track_video(filevideo, model, time)
  File "/home/alanromero/crowd-counting/src/inference/System/App/OrionProcedures/OrionProcedures.py", line 132, in track_video
    results = model.track(source=frame, persist=True, classes=0)
  File "/home/alanromero/anaconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 259, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "/home/alanromero/anaconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/alanromero/anaconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 238, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/alanromero/anaconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 194, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/alanromero/anaconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/alanromero/anaconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 253, in stream_inference
    preds = self.inference(im, *args, **kwargs)
  File "/home/alanromero/anaconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 133, in inference
    return self.model(im, augment=self.args.augment, visualize=visualize)
  File "/home/alanromero/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/alanromero/anaconda3/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 333, in forward
    y = self.model(im, augment=augment, visualize=visualize) if augment or visualize else self.model(im)
  File "/home/alanromero/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/alanromero/anaconda3/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 45, in forward
    return self.predict(x, *args, **kwargs)
  File "/home/alanromero/anaconda3/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 62, in predict
    return self._predict_once(x, profile, visualize)
  File "/home/alanromero/anaconda3/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 82, in _predict_once
    x = m(x)  # run
  File "/home/alanromero/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/alanromero/anaconda3/lib/python3.10/site-packages/ultralytics/nn/modules/block.py", line 182, in forward
    return self.cv2(torch.cat(y, 1))
  File "/home/alanromero/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/alanromero/anaconda3/lib/python3.10/site-packages/ultralytics/nn/modules/conv.py", line 42, in forward_fuse
    return self.act(self.conv(x))
  File "/home/alanromero/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/alanromero/anaconda3/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/alanromero/anaconda3/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,

>>>>>>>>>>>>>>[ERROR_DESC]<<<<<<<<<<<<<<<

  [KeyboardInterrupt]:

>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<

